version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    allow:
      - dependency-name: "alpinejs"
      - dependency-name: "@alpinejs/persist"
      - dependency-name: "htmx.org"
      - dependency-name: "tailwindcss"
      - dependency-name: "postcss"
      - dependency-name: "autoprefixer"
      - dependency-name: "@iconify/json"
      - dependency-name: "@iconify/tailwind"