name: format

on:
    push:

jobs:
    format:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v1
            - run: bun install --frozen-lockfile
            - run: make format
            - uses: stefanzweifel/git-auto-commit-action@v5
              with:
                commit_message: "perf: formatting (ci)"